In [92]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import nltk
from nltk import word_tokenize
from nltk.corpus import stopwords
import re

In [93]:
df= pd.read_csv("salary_indeed.csv")

In [94]:
df.shape

(4884, 9)

In [95]:
df.fillna("None", inplace = True)

In [96]:
df.Title.str.lower().str.contains('cdi', regex=True).astype(int).sum()

112

In [97]:
def type_de_contrat(row):
    title = row["Title"].lower()
    desc = row["Description"].lower()
    #search for CDI in title and desc
    if bool(re.search('cdi',title)):
        row["cdi"]=1
    elif bool(re.search('cdi',desc)) and not bool(re.search('stage',title)):
        row["cdi"]=1
    else:
        row["cdi"]=0
    #search for stage in title and desc
    if bool(re.search(r'stage|intern',title)):
        row["stage"]=1 
    else:
        row["stage"]=0
    #search for freelance in title and desc
    if bool(re.search('freelance',title)):
        row["freelance"]=1
    elif bool(re.search(r'type\sd(\\?\'emploi\s?|e\scontrat):?.{0,26}freelance',desc)) and not bool(re.search('freelance',title)):
        row["freelance"]=1
    else:
        row["freelance"]=0
    #search for CDD in title and desc
    if bool(re.search('cdd',title)):
        row["cdd"]=1
    elif bool(re.search(r'type\sd(\\?\'emploi\s?|e\scontrat):?.{0,26}cdd',desc)) and not bool(re.search('cdd',title)):
        row["cdd"]=1 
    else:
        row["cdd"]=0
        
    return row

In [98]:
df= df.apply(type_de_contrat, axis=1)

In [99]:
df

,_id,Title,Company,Location,Salary,Description,Date,Job_Search,Department_Search,cdi,stage,freelance,cdd
0,p_00198c04b7c86195,Développeuse / Développeur Stack Elastic Search,LexisNexis,Paris (75),None,Développeur Sénior Java Elastic Search Respon...,07/09/2019,Développeur,75,0,0,0,0
1,p_0020213df500f7d8,Développeur Front End F/H,KP2I,Paris 1er (75),None,Dans le cadre de la refonte du site e-commerce...,01/10/2019,Développeur,75,0,0,0,0
2,p_0030c303451b137b,Data Analyst (H/F) - Alternance,Nexity,Paris 8e (75),None,Job Description Dans le cadre de son programm...,24/09/2019,Data,75,0,0,0,0
3,p_003ef0f6960ff453,"INTERNSHIP POSITION, Evaluation of the aircraf...",Airbus,Toulouse (31),None,AIRBUS SAS Airbus is a global leader in aerona...,25/09/2019,Data,Haute-Garonne,0,1,0,0
4,p_005290833c76d0fe,Des Développeurs Java JEE (H/F),FrançAsie,Nantes (44),None,FrançAsie recrute pour notre client une Sociét...,07/09/2019,Développeur,Loire-Atlantique,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4879,pj_fecbe7703c9699cd,Digital Data Analyst (H/F) - H/F,Aravati,Paris (75),55 000 € par an,R / Python / Adobe-analytics / At-internet / G...,None,Data,75,1,0,0,0
4880,pj_ff0927732dd43f05,Développeur front end et React native (H/F),HR-TEAM,Paris (75),None,Nous recherchons un ingénieur Frontend et Reac...,None,Développeur,75,0,0,0,0
4881,pj_ff574a8056c960a5,Ingénieur Devops (H/F),ACCELITE,Paris (75),None,"ACCELITE, société de service informatique, est...",None,Développeur,75,0,0,0,0
4882,pj_ff708f368534bb0b,Analyste Développeur SAP Full Stack H/F,Michael Page,Paris 1er (75),None,"Rattaché au Manager SAP développement, vous av...",None,Développeur,75,0,0,0,0
4883,pj_ffcef54f4f9d5139,Développeur PL/SQL - H/F,Actif Solution,Lyon (69),None,Poste et missions : Au sein d'un centre de dév...,None,Développeur,Rhône,0,0,0,0

In [100]:
#df["freelance_test"]=df.Description.str.lower().str.contains('freelance[^r][^s]?', regex=True).astype(int)

In [101]:
#print(not bool(re.search('fabi',df.Title[0].lower())))

In [102]:
#df["cdi_test"]=df.Description.str.lower().str.contains('cdi', regex=True).astype(int)

In [103]:
#list(df[df.freelance_test==1].index)

In [104]:
#df.iloc[3516].Description

In [105]:
#

In [106]:
#df.Description.str.lower().str.contains(r'type\sd(\\?\'emploi\s?|e\scontrat):?.{0,26}cdd', regex=True).astype(int).sum()

In [107]:
df.iloc[0].Description

"Développeur Sénior Java Elastic Search  Responsabilités  Au sein du Département des Technologies et des Systèmes d’Information de LexisNexis, vous interviendrez en tant que Développeur Sénior Elastic Search sur un produit de gestion d’information juridique. Vous serez intégré au sein d’une équipe qui développe un produit de recherche, de navigation et d’analytiques d’un corpus juridique.  Périmètre du poste  Ø Concevoir et développer l’intégration du moteur Elastic Search dans le backend du produit. Ø Gérer la performance et la haute disponibilité sur 30M de contenus juridiques hétérogènes et de structure complexe avec un flux additionnel annuel d’environ 2M. Ø Implémenter une pertinence selon des règles de pondération, parfois complexes, définies par le métier. Ø Mettre en place un système d’amélioration continue de la performance et pertinence, en tenant compte du flux et de l’évolution de l’actualité juridique (fournie par nos experts) Ø Développer des mécanismes propres comme les agrégations de documents et adapter le calcul de pertinence et le ranking en conséquence Ø Coupler les fonctions de recherche à un graph (base de graph) représentant un grand nombre de combinaisons de liens inter-documents Ø Avoir une expérience dans la détection de l’intention utilisateur et/ou des connaissances NLP seraient un plus  Compétences  Ø Formation BAC+5 (école d’ingénieur en informatique) Ø Expérience de 5 ans minimum sur du développement Elastic Search en java Ø Systèmes : Linux (Ubuntu), Windows Ø Connaissance de la méthode Agile Scrum Ø Bonne connaissance des bases de données relationnelles, NoSQL et des bases de graph Ø Maitrise du développement web non bloquant / évènementiel Ø Stack technique principale à considérer : Java, Vertex, RabbitMQ, RDF, XML Ø Connaissances SysOps, cloud public / privé AWS, infrastructure as code Ø Connaissance de la stack DevOps sera un plus : Consul, Ansible, Jenkins, Sonar, Git, Docker, Kubernetes, TerraForm Ø Très bonnes qualités relationnelles  Compétences humaines  Vous êtes passionné(e) par le développement et vous assurez une veille technologique; Vous avez un excellent esprit d'analyse et de synthèse ; Vous êtes pragmatique, autonome, et vous toujours force de proposition de solutions ; Vous accordez énormément d'importance à la qualité et la fiabilité de vos réalisations."

In [108]:
df.cdi.sum()

1407

In [109]:
df.Description.str.lower().str.contains(r'cdi', regex=True).astype(int).sum()

1362

In [110]:
df.freelance.sum()

203

In [111]:
df.stage.sum()

299

In [112]:
df.cdd.sum()

40

In [113]:
df[(df["cdi"]==0) & (df['freelance']==0) & (df['stage']==0) & (df['cdd']==0)]

,_id,Title,Company,Location,Salary,Description,Date,Job_Search,Department_Search,cdi,stage,freelance,cdd
0,p_00198c04b7c86195,Développeuse / Développeur Stack Elastic Search,LexisNexis,Paris (75),None,Développeur Sénior Java Elastic Search Respon...,07/09/2019,Développeur,75,0,0,0,0
1,p_0020213df500f7d8,Développeur Front End F/H,KP2I,Paris 1er (75),None,Dans le cadre de la refonte du site e-commerce...,01/10/2019,Développeur,75,0,0,0,0
2,p_0030c303451b137b,Data Analyst (H/F) - Alternance,Nexity,Paris 8e (75),None,Job Description Dans le cadre de son programm...,24/09/2019,Data,75,0,0,0,0
5,p_005e0220f8124f08,LEAD DEVELOPPEUR PYTHON F/H,OTTEO,Paris 13e (75),None,Votre mission principale sera d' assurer l'in...,18/09/2019,Développeur,75,0,0,0,0
6,p_00677a6d6bd2fa2e,Consultant Confirmé BI / Data Intelligence (H/F),ASI,Lyon (69),None,"Pour la réalisation de nos projets, essentiell...",07/12/2018,Data,Rhône,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4875,pj_fc87c600387c3e85,Developpeur Java Back-end,Gentis Recruitment SAS,Paris (75),50 € par heure,"Bonjour, Notre client est une startup, jeune ...",None,Développeur,75,0,0,0,0
4880,pj_ff0927732dd43f05,Développeur front end et React native (H/F),HR-TEAM,Paris (75),None,Nous recherchons un ingénieur Frontend et Reac...,None,Développeur,75,0,0,0,0
4881,pj_ff574a8056c960a5,Ingénieur Devops (H/F),ACCELITE,Paris (75),None,"ACCELITE, société de service informatique, est...",None,Développeur,75,0,0,0,0
4882,pj_ff708f368534bb0b,Analyste Développeur SAP Full Stack H/F,Michael Page,Paris 1er (75),None,"Rattaché au Manager SAP développement, vous av...",None,Développeur,75,0,0,0,0
4883,pj_ffcef54f4f9d5139,Développeur PL/SQL - H/F,Actif Solution,Lyon (69),None,Poste et missions : Au sein d'un centre de dév...,None,Développeur,Rhône,0,0,0,0

In [114]:
'''import pandas as pd
import numpy as np 
import string
import re

df = pd.read_csv("/Users/fabi/Documents/Data AI Ecouen/PROJECTS/ML/app_dash 2/data/df.csv")
#df = pd.read_csv("/Users/fabi/Documents/Data AI Ecouen/PROJECTS/ML/MAJ/salary_indeed.csv")

#df["Doctorat"] = df.Description.str.lower().str.contains(r'\bdoctorat\b', regex=True).astype(int)
#df["Doctorat"] 
#df["Bac & Bac Pro"] = df.Description.str.lower().str.contains(r'\bbac[?!\s\S+]\b|\bniveaux?iv+\b|\b(baccalaur[ée]at)\b|\b(baccalaur[ée]at\spro)|\b(bac\spro)', regex=True).astype(int)
df["BTS"] = df.Description.str.lower().str.contains(r'\bbts\b', regex=True).astype(int)
df["Deug"] = df.Description.str.lower().str.contains(r'\bdeug\b|\bniveaux?iii+\b|\bbac[\s\S]?[+]?[\s\S]2\b', regex=True).astype(int)
df["DUT"] = df.Description.str.lower().str.contains(r'\bdut\b', regex=True).astype(int)
df["IUT"] = df.Description.str.lower().str.contains(r'\biut\b', regex=True).astype(int)
df["Licence"] = df.Description.str.lower().str.contains(r'\blicence\b|\bniveaux?ii+\b|\bbac[\s\S]?[+]?[\s\S]3\b', regex=True).astype(int)
df["Master"] = df.Description.str.lower().str.contains(r'\bmaster\b|\bniveaux?i+\b|\bbac[\s\S]?[+]?[\s\S]5\b|\bmba\b', regex=True).astype(int)
df["Doctorat"] = df.Description.str.lower().str.contains(r'\bdoctorat\b|\bbac[\s\S]?[+]?[\s\S]8\b', regex=True).astype(int)
df["Ecole_Ingénieure"] = df.Description.str.lower().str.contains(r'\b[eé]cole\sing[ée]nieure?\b', regex=True).astype(int)

df '''

'import pandas as pd\nimport numpy as np \nimport string\nimport re\n\ndf = pd.read_csv("/Users/fabi/Documents/Data AI Ecouen/PROJECTS/ML/app_dash 2/data/df.csv")\n#df = pd.read_csv("/Users/fabi/Documents/Data AI Ecouen/PROJECTS/ML/MAJ/salary_indeed.csv")\n\n#df["Doctorat"] = df.Description.str.lower().str.contains(r\'\x08doctorat\x08\', regex=True).astype(int)\n#df["Doctorat"] \n#df["Bac & Bac Pro"] = df.Description.str.lower().str.contains(r\'\x08bac[?!\\s\\S+]\x08|\x08niveaux?iv+\x08|\x08(baccalaur[ée]at)\x08|\x08(baccalaur[ée]at\\spro)|\x08(bac\\spro)\', regex=True).astype(int)\ndf["BTS"] = df.Description.str.lower().str.contains(r\'\x08bts\x08\', regex=True).astype(int)\ndf["Deug"] = df.Description.str.lower().str.contains(r\'\x08deug\x08|\x08niveaux?iii+\x08|\x08bac[\\s\\S]?[+]?[\\s\\S]2\x08\', regex=True).astype(int)\ndf["DUT"] = df.Description.str.lower().str.contains(r\'\x08dut\x08\', regex=True).astype(int)\ndf["IUT"] = df.Description.str.lower().str.contains(r\'\x08iut\x08\', regex=True).astype(int)\ndf["Licence"] = df.Description.str.lower().str.contains(r\'\x08licence\x08|\x08niveaux?ii+\x08|\x08bac[\\s\\S]?[+]?[\\s\\S]3\x08\', regex=True).astype(int)\ndf["Master"] = df.Description.str.lower().str.contains(r\'\x08master\x08|\x08niveaux?i+\x08|\x08bac[\\s\\S]?[+]?[\\s\\S]5\x08|\x08mba\x08\', regex=True).astype(int)\ndf["Doctorat"] = df.Description.str.lower().str.contains(r\'\x08doctorat\x08|\x08bac[\\s\\S]?[+]?[\\s\\S]8\x08\', regex=True).astype(int)\ndf["Ecole_Ingénieure"] = df.Description.str.lower().str.contains(r\'\x08[eé]cole\\sing[ée]nieure?\x08\', regex=True).astype(int)\n\ndf '

In [ ]:
df["BTS"] = df.Description.str.lower().str.contains(r'\bbts\b', regex=True).astype(int)

df["Deug"] = df.Description.str.lower().str.contains(r'\bdeug\b|\bniveaux?iii+\b|\bbac[\s\S]?[+]?[\s\S]2\b', regex=True).astype(int)

df["DUT"] = df.Description.str.lower().str.contains(r'\bdut\b', regex=True).astype(int)

df["IUT"] =df.Description.str.lower().str.contains(r'\biut\b', regex=True).astype(int)

df["Licence"] = df.Description.str.lower().str.contains(r'\blicence\b|\bniveaux?ii+\b|\bbac[\s\S]?[+]?[\s\S]3\b|\b\(?bac\s?\+\s?2\s?[\/àeo][tu]?\s?(bac)?\s?\+?\s?5\)?\b|(\b\(?bac\s?\+\s?2\s?[\/àeo][tu]?\s?(bac)?\s?\+?\s?3\)?\b)', regex=True).astype(int)

df["Master"] = df.Description.str.lower().str.contains(r'\bmaster\b|\bniveaux?i+\b|\bbac[\s\S]?[+]?[\s\S]5\b|\bmba\b|(\bbac\s?\+\s?4\s?[\/à]\s?(bac)?\+?5\b)|(\bbac\s?\+\s?4\s?(ou)\s?(bac)?\s?\+?\s?5\b)', regex=True).astype(int)

df["Doctorat"] = df.Description.str.lower().str.contains(r'\bdoctorat\b|\bbac[\s\S]?[+]?[\s\S]8\b', regex=True).astype(int)

df["Ecole_Ingénieure"] = df.Description.str.lower().str.contains(r'\b[eé]cole\sing[ée]nieur[e]?\b|\bing[ée]nieur[e]\b', regex=True).astype(int)

In [123]:
#list(df[df["Master"]==1].index)

In [124]:
df.iloc[702].Description

'Email is the universal communication tool for work. It’s where you discuss work, answer questions, and talk to all of your customers, vendors, and partners. But email wasn’t made for business and hasn’t evolved to help you work with a team. So you’re dropping the ball, missing important context, and relying on many siloed apps that make you less productive as a whole.  With more than 5,000 customers and $79 million in funding from Sequoia, Threshold (formerly DFJ), and others, Front is reinventing the inbox so people can accomplish more together. We’ve created one place where you communicate internally and externally, gain context about customers and projects, and access all your other tools so you can be more efficient, more fulfilled, and ultimately happier at work.  As an intern/co-op on our engineering team, you’ll help us reinvent the inbox for teams by working on high-impact projects like building new product features, improving our integrations framework, and optimizing customer onboarding. You’ll receive dedicated mentorship and learn from a world-class engineering and product team that’s experiencing rapid growth. Along the way, you’ll also become a part of Front’s award-winning company culture and learn how a successful organization scales. This is an exciting opportunity to have a path into a full-time role within the Front Engineering team, upon a successful internship. What will you be doing? Partner closely with a dedicated engineering mentor to grow throughout the internship inline with your career ambitions What skills and experience do you need? Recently completed or pursuing a Bachelor’s degree in Computer Science, graduating in 2019 or early 2020 Strong attention to detail and problem solving ability Genuine curiosity for learning and desire for improvement Product-minded: committed to building a great experience for our users Bonus Experience with Javascript, React, or node.js Previous software engineering internship experience Front provides equal employment opportunities (EEO) to all employees and applicants for employment without regard to race, color, religion, sex, sexual orientation, gender identity, national origin, age or disability.'

In [130]:
pd.set_option('display.max_columns', None)
df.sample(20)

,_id,Title,Company,Location,Salary,Description,Date,Job_Search,Department_Search,cdi,stage,freelance,cdd,BTS,Deug,DUT,IUT,Licence,Master,Doctorat,Ecole_Ingénieure
2685,p_9f804721c3c0880b,Développeur BackEnd JAVA EE H/F,CNAV,Paris (75),None,"Contexte L'Assurance Retraite, 1ère caisse de ...",23/09/2019,Développeur,75,0,0,0,0,0,0,0,0,0,1,0,0
1735,p_65b81e1754cd0f32,Stage Ingénieur système avion HUD et analyse B...,Expleo,Toulouse (31),None,Aéronautique Midi-Pyrénées - TOULOUSEStage 201...,02/10/2019,Data,Haute-Garonne,0,1,0,0,0,0,0,0,0,1,0,0
957,p_3568101e51f42658,Full Stack Software Engineer,DELAIR TECH,Paris (75),None,"Toulouse or Paris, Permanent contract, Full ti...",07/02/2019,Développeur,75,0,0,0,0,0,0,0,0,0,0,0,0
788,p_2bc0c86a1b7a29a4,Développeur Java full stack H/F,Geofit,Nantes (44),None,Accueil Offres d'emploi Il y a 1 mois Développ...,09/05/2019,Développeur,Loire-Atlantique,1,0,0,0,0,1,0,0,1,0,0,0
2294,p_8703a3d5c169ad15,Développeur Java EE expérimenté (H/F),Atos,Bordeaux (33),None,A propos d'Atos Atos est un leader internation...,25/09/2019,Développeur,Gironde,0,0,0,0,0,0,0,0,0,1,0,0
431,p_175c623f8448eb32,Cloud Devops Engineer,PeopleDoc,Paris (75),None,PeopleDoc is on a mission to revolutionize how...,08/12/2018,Développeur,75,0,0,0,0,0,0,0,0,0,0,0,0
3033,p_b42cccc2d950acec,INGENIEUR D'AFFAIRES IA BIG DATA TEXT MINING,SOFTWARESELLING FRANCE,Paris (75),60 000 € - 70 000 € par an,INGENIEUR D’AFFAIRES EN SOLUTIONS “TEXT MINING...,10/09/2019,Data,75,1,0,0,0,0,0,0,0,0,1,0,0
4329,p_ff324245984de0eb,"Product Manager, Data & AI",Mauna Kea Technologies,Paris (75),None,Mauna Kea Technologies ( www.maunakeatech.com ...,03/10/2019,Data,75,0,0,0,0,0,0,0,0,0,1,0,0
4774,pj_cbe645d190bf357b,Ingénieur développeur R&D en Finance de Marché...,JUMP Technology,Paris (75),None,Ingénieur développeur R&D en Finance de Marché...,None,Développeur,75,0,1,0,0,0,0,0,0,0,0,0,0
1631,p_5e383aba504b04a1,Développeur de réseau franchise (h/f) à Rillie...,XEFI,Rillieux-la-Pape (69),None,"Fondé en 1997, XEFI (anciennement CFI) est auj...",07/09/2019,Développeur,Rhône,0,0,0,0,0,0,0,0,0,0,0,0
3213,p_bf4ac3552f252976,Développeur Java/JEE H/F,Seek Recrutement,Bordeaux (33),42 000 € - 48 000 € par an,De formation supérieure en informatique de ge...,27/09/2019,Développeur,Gironde,1,0,0,0,0,0,0,0,0,0,0,0
4327,p_ff2773359491ce8e,Développeur(euse) JAVA J2EE F/H,HAUBAN,Toulouse (31),None,Pour accompagner un de nos clients dans le dév...,19/09/2019,Développeur,Haute-Garonne,0,0,0,0,0,0,0,0,0,1,0,0
33,p_01a44477a6c11160,Développeur Frond End Angular (H/F) / Freelance,insitoo-it,Lyon (69),None,Insitoo est une plateforme collaborative de pr...,10/09/2019,Développeur,Rhône,0,0,1,0,0,0,0,0,0,0,0,0
3160,p_bbe3f76c4be666ab,"DÉVELOPPEUR ASP.NET, C# - Back-End ou Full Sta...",INSURED Services,Toulouse (31),None,"Rejoignez une jeune entreprise de l'Assurtech,...",17/09/2019,Développeur,Haute-Garonne,1,0,0,0,0,0,0,0,0,0,0,0
4782,pj_d0dbe22eb6c5b712,Chef de projets Data Science,soft.computing,Paris (75),None,"Soft Computing, Publicis Groupe, est leader du...",None,Data,75,0,0,0,0,0,0,0,0,0,0,0,0
1281,p_48f85f97008511bb,Développeur junior H/F,PMU,Paris (75),None,"Au sein de l'équipe engagement clients, en lie...",21/09/2019,Développeur,75,0,0,0,0,0,0,0,0,0,1,0,0
2384,p_8c4dbe1bace10249,Développeuse ou développeur Java / Search,Adelean,Paris (75),None,"Aujourd’hui, nous recherchons une développeuse...",12/09/2019,Développeur,75,0,0,0,0,0,0,0,0,0,0,0,0
970,p_368514bdda2f554a,INGENIEUR DATA MINING F/H,FACTSET JCF,Paris 9e (75),None,Notre département d’ingénierie est responsable...,26/09/2019,Data,75,0,0,0,0,0,0,0,0,0,0,0,0
306,p_0f250fd7d892ca4b,DEVELOPPEURS MOBILE ANDROID ET/OU IOS H/F,TALENTS RH,Toulouse (31),None,"TALENTS RH, société de recrutement spécialisée...",08/09/2019,Développeur,Haute-Garonne,0,0,0,0,0,0,0,0,0,0,0,0
31,p_019d01b7494dc632,Référent fonctionnel et données - Data manager...,GARCIN FINANCES ET PARTICIPATIONS,Corbas (69),40 000 € - 45 000 € par an,Vous souhaitez participer à la structuration d...,10/09/2019,Data,Rhône,1,0,0,0,0,0,0,0,0,1,0,0

In [126]:
df.freelance.sum()

203

In [127]:
#df["test"]=df.Title.str.lower().str.contains(r'intern', regex=True).astype(int)

In [128]:
#df.iloc[3].Title

"INTERNSHIP POSITION, Evaluation of the aircraft data traffic's cost (m/f)"

In [129]:
#df[df.test==1]

AttributeError: 'DataFrame' object has no attribute 'test'